[project]
name = "nx-decomp-tools"
version = "0.0.0"
requires-python = ">=3.14"
dependencies = [
    "asm-differ",
    "colorama>=0.4.6",
    "cxxfilt>=0.3.0",
    "gitpython>=3.1.62",
    "toml>=0.10.2",
]

[tool.uv.sources]
asm-differ = { git = "https://github.com/simonlindholm/asm-differ", rev = "0dd09af8f8008f1f880327cf0aca3b26d2562ea2" }

[tool.uv.build-backend]
module-root = ""

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
